"""Centralized, dynamic configuration engine.

Settings are powered by ``pydantic-settings`` and loaded, in priority order,
from:

1. explicit keyword overrides passed to :func:`get_settings` / constructor,
2. environment variables (``FOO_BAR`` maps to ``foo_bar``),
3. a ``.env`` file on disk (never committed - see ``.env.example``).

A module-level :func:`get_settings` returns a cached singleton while
:func:`reload_settings` busts the cache so long-running processes can pick
up configuration changes without a restart - hence *dynamic*.

Usage::

    from src.config import get_settings

    settings = get_settings()
    print(settings.yolo_model_path, settings.otel_service_name)
"""

from __future__ import annotations

from enum import Enum
from functools import lru_cache
from typing import Any

from pydantic import Field, HttpUrl, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

__all__ = ["Environment", "Settings", "get_settings", "parse_resource_attributes", "reload_settings"]


class Environment(str, Enum):
    """Deployment environment - constrained to the supported set."""

    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"


class Settings(BaseSettings):
    """All runtime-tunable knobs for the HUD engine."""

    # ----------------------------------------------------------------- source
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=False,
        # validate_default=True so the bundled defaults are coerced through the
        # same validators as env-provided values.
        validate_default=True,
    )

    # ----------------------------------------------------------------- YOLO
    yolo_model_path: str = Field(
        default="yolov11n.pt",
        description="Local path or HF repo id for the YOLOv11 detection model.",
    )
    yolo_confidence_threshold: float = Field(
        default=0.40,
        ge=0.0,
        le=1.0,
        description="Minimum confidence for a detection to be kept.",
    )
    yolo_iou_threshold: float = Field(
        default=0.50,
        ge=0.0,
        le=1.0,
        description="IOU threshold for class-agnostic non-max suppression.",
    )

    # ----------------------------------------------------------------- OSM
    overpass_endpoint_url: HttpUrl = Field(
        default=HttpUrl("https://overpass-api.de/api/interpreter"),
        description="Overpass API QL endpoint queried for road policy.",
    )
    overpass_timeout_seconds: int = Field(
        default=25,
        ge=1,
        description="HTTP timeout (seconds) for Overpass requests.",
    )

    # ----------------------------------------------------------------- VLM
    vlm_model_id: str = Field(
        default="Qwen/Qwen2-VL-2B-Instruct",
        description="Hugging Face model identifier for the scene-understanding VLM.",
    )
    vlm_max_tokens: int = Field(default=512, ge=1, description="Max tokens generated by the VLM.")
    vlm_temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=1.0,
        description="VLM sampling temperature.",
    )

    # ----------------------------------------------------------------- fallbacks
    osm_fallback_enabled: bool = Field(
        default=True,
        description="When True, serve a cached/derived road policy if Overpass fails.",
    )
    vlm_fallback_enabled: bool = Field(
        default=True,
        description="When True, degrade gracefully if the VLM errors.",
    )
    max_retry_attempts: int = Field(default=3, ge=0, description="Default retry ceiling for transient calls.")
    retry_backoff_base_seconds: float = Field(
        default=0.5,
        ge=0.0,
        description="Base delay (seconds) for exponential backoff.",
    )

    # ----------------------------------------------------------------- telemetry
    otel_service_name: str = Field(
        default="uae-scooter-hud-engine",
        description="OpenTelemetry ``service.name`` resource attribute.",
    )
    otel_endpoint: HttpUrl | None = Field(
        default=None,
        description="Optional OTLP HTTP endpoint (e.g. an otel-collector).",
    )
    otel_resource_attributes: str = Field(
        default="",
        description="Extra OTel resource attributes as 'k=v,k2=v2' (human friendly in .env).",
    )
    otel_sampling_ratio: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Trace sampling ratio (1.0 = sample everything).",
    )
    otel_export_console: bool = Field(
        default=True,
        description="Emit spans to the console exporter (useful in dev).",
    )
    otel_export_otlp: bool = Field(
        default=False,
        description="Export spans to the configured ``otel_endpoint`` over OTLP/HTTP.",
    )
    otel_bsp_schedule_delay_ms: int = Field(
        default=5000,
        ge=0,
        description="BatchSpanProcessor schedule delay (ms).",
    )

    # ----------------------------------------------------------------- runtime
    environment: Environment = Field(
        default=Environment.DEVELOPMENT,
        description="Deployment environment.",
    )
    log_level: str = Field(
        default="INFO",
        description="Stdlib logging level name.",
    )

    # ----------------------------------------------------------------- parsing
    @field_validator("log_level", mode="after")
    @classmethod
    def _normalise_and_validate_level(cls, v: str) -> str:
        normalised = v.strip().upper()
        if normalised not in {"CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG", "NOTSET"}:
            raise ValueError(f"log_level must be a valid stdlib level, got {v!r}")
        return normalised

    @field_validator("yolo_model_path")
    @classmethod
    def _model_path_not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("yolo_model_path must not be empty")
        return v

    @model_validator(mode="after")
    def _self_check(self) -> Settings:
        return self

    # ----------------------------------------------------------------- helpers
    @property
    def otel_resource_attributes_parsed(self) -> dict[str, str]:
        """The raw ``k=v,k2=v2`` string parsed into a dictionary."""
        return parse_resource_attributes(self.otel_resource_attributes)

    @property
    def resource_attributes(self) -> dict[str, str]:
        """Merged OTel resource attributes (service.name always present)."""
        attrs = self.otel_resource_attributes_parsed
        attrs.setdefault("service.name", self.otel_service_name)
        attrs.setdefault("environment", self.environment.value)
        return attrs

    @property
    def is_production(self) -> bool:
        return self.environment is Environment.PRODUCTION

    def for_log_record(self) -> dict[str, Any]:
        """A redacted, JSON-serialisable snapshot safe to emit on log lines."""
        return {
            "environment": self.environment.value,
            "otel_service_name": self.otel_service_name,
            "vlm_model_id": self.vlm_model_id,
            "yolo_confidence_threshold": self.yolo_confidence_threshold,
            "osm_fallback_enabled": self.osm_fallback_enabled,
            "vlm_fallback_enabled": self.vlm_fallback_enabled,
        }


def parse_resource_attributes(value: Any) -> dict[str, str]:
    """Normalise an OpenTelemetry resource-attributes description.

    Accepts ``"k=v,k2=v2"`` / ``"k=v;k2=v2"`` strings (as used in ``.env``),
    a mapping, or a sequence of mappings/strings - returning a flat
    ``dict[str, str]``.
    """
    if value is None or value == "":
        return {}
    if isinstance(value, dict):
        return {str(k): str(val) for k, val in value.items()}
    if isinstance(value, (list, tuple)):
        out: dict[str, str] = {}
        for item in value:
            out.update(parse_resource_attributes(item))
        return out
    if isinstance(value, str):
        pairs: dict[str, str] = {}
        for segment in value.replace(";", ",").split(","):
            segment = segment.strip()
            if not segment:
                continue
            if "=" not in segment:
                raise ValueError(f"resource attribute segment must be k=v, got {segment!r}")
            key, val = segment.split("=", 1)
            pairs[key.strip()] = val.strip()
        return pairs
    raise ValueError(f"unsupported resource attributes input: {type(value)!r}")


@lru_cache(maxsize=8)
def _build_settings(
    env_path: str | None = None,
    overrides: tuple[tuple[str, Any], ...] | None = None,
) -> Settings:
    """Internal factory backing :func:`get_settings`.

    ``env_path`` overrides the default ``.env`` location; ``overrides`` is a
    sequence of ``(key, value)`` pairs applied as init kwargs (highest
    priority). Both values participate in the cache key so different inputs
    yield different singletons.
    """
    kwargs: dict[str, Any] = {}
    if env_path:
        kwargs["_env_file"] = env_path
    if overrides:
        kwargs.update(dict(overrides))
    return Settings(**kwargs)


def get_settings(env_path: str | None = None, **overrides: Any) -> Settings:
    """Return the cached :class:`Settings` singleton.

    Pass ``**overrides`` to apply ad-hoc overrides on top of the loaded
    file/environment without writing to disk, e.g.::

        settings = get_settings(yolo_confidence_threshold=0.6)

    Override values are funnelled through :func:`_build_settings`, whose
    ``lru_cache`` is keyed on a *hashable* tuple - keeping the cache safe
    even when callers pass keyword overrides.
    """
    ov = tuple(sorted(overrides.items())) if overrides else None
    return _build_settings(env_path, ov)


def reload_settings(env_path: str | None = None, **overrides: Any) -> Settings:
    """Drop the cached settings and rebuild them - a *dynamic* reconfiguration."""
    _build_settings.cache_clear()
    return get_settings(env_path, **overrides)
